services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/secure_app
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
